---

image: docker-reg.test-visocon.com:5000/visocon/rails-test

services:
  - mongo:3.2

variables:
  MONGO_HOST: mongo

before_script:
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  - ruby -v
  - which ruby
  - cp config/mongoid.yml.example config/mongoid.yml
  - cp config/secrets.yml.example config/secrets.yml
  - gem install bundler --no-ri --no-rdoc
  - bundle install --jobs $(nproc) --without production development --path=/cache/bundler
  - RAILS_ENV=test bundle exec rails db:mongoid:create_indexes

rspec:
  script: bundle exec rspec --format documentation
  tags:
    - ruby
    - mongo

rubocop:
  before_script:
    - gem install rubocop --no-ri --no-doc
  script: rubocop -D
  tags:
    - ruby
