AllCops:
  Include:
    - Rakefile
    - config.ru
    - lib/**/*.rake
  Exclude:
    - bin/*
    - db/schema.rb
    - spec/support/authorization_helpers.rb

Style/FrozenStringLiteralComment:
  Enabled: false

Rails:
  Enabled: true
