AllCops:
  Include:
    - Rakefile
    - config.ru
    - lib/**/*.rake
  Exclude:
    - Gemfile
    - bin/*
    - db/schema.rb
    - spec/**/*
    - config/environments/*

Style/FrozenStringLiteralComment:
  Enabled: false

Rails:
  Enabled: true

Rails/FilePath:
  Enabled: false

Security/YAMLLoad:
  Enabled: false
