development:
  adapter: mysql2
  encoding: utf8
  host: localhost
  database: slack_development
  username: root
  password: root
  port: 3306
  socket: /Applications/MAMP/tmp/mysql/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  host: localhost
  database: slack_test
  username: root
  password: root
  port: 3306
  socket: /Applications/MAMP/tmp/mysql/mysql.sock
