development:
  eyeson_api: https://localhost:3001
  internal_pwd: config/certs/internal.yml
  setup_complete_url: https://eyeson.team/slack/success
  faq_url: https://eyeson.team/slack/faq
  slack_token: "<%= Rails.application.secrets.slack_token %>"
  slack_key: "<%= Rails.application.secrets.slack_key %>"
  slack_secret: "<%= Rails.application.secrets.slack_secret %>"

test:
  eyeson_api: http://test.host/eyeson/api
  internal_pwd: /mnt/certs/internal.yml
  setup_complete_url: https://eyeson.team/slack/success
  faq_url: https://eyeson.team/slack/faq
  slack_token: "<%= Rails.application.secrets.slack_token %>"
  slack_key: "<%= Rails.application.secrets.slack_key %>"
  slack_secret: "<%= Rails.application.secrets.slack_secret %>"

staging:
  eyeson_api: https://api.test-visocon.com
  internal_pwd: /mnt/certs/internal_api.yml
  setup_complete_url: https://eyeson.team/slack/success
  faq_url: https://eyeson.team/slack/faq
  slack_token: "<%= Rails.application.secrets.slack_token %>"
  slack_key: "<%= Rails.application.secrets.slack_key %>"
  slack_secret: "<%= Rails.application.secrets.slack_secret %>"

integration:
  eyeson_api: https://api.dev-visocon.com
  internal_pwd: /mnt/certs/internal_api.yml
  setup_complete_url: https://eyeson.team/slack/success
  faq_url: https://eyeson.team/slack/faq
  slack_token: "<%= Rails.application.secrets.slack_token %>"
  slack_key: "<%= Rails.application.secrets.slack_key %>"
  slack_secret: "<%= Rails.application.secrets.slack_secret %>"

production:
  eyeson_api: https://api.eyeson.team
  internal_pwd: /mnt/certs/internal_api.yml
  setup_complete_url: https://eyeson.team/slack/success
  faq_url: https://eyeson.team/slack/faq
  slack_token: "<%= Rails.application.secrets.slack_token %>"
  slack_key: "<%= Rails.application.secrets.slack_key %>"
  slack_secret: "<%= Rails.application.secrets.slack_secret %>"
