development:
  eyeson_api: https://localhost:3001
  eyeson_account_api: https://account.dev-visocon.com/api
  setup_complete_url: https://eyeson.team/slack/success
  faq_url: https://eyeson.team/slack/faq

test:
  eyeson_api: http://test.host/eyeson/api
  eyeson_account_api: http://localhost:3001
  setup_complete_url: https://eyeson.team/slack/success
  faq_url: https://eyeson.team/slack/faq

staging:
  eyeson_api: https://api.test-visocon.com
  eyeson_account_api: https://account.dev-visocon.com/api
  setup_complete_url: https://eyeson.team/slack/success
  faq_url: https://eyeson.team/slack/faq

integration:
  eyeson_api: https://api.dev-visocon.com
  eyeson_account_api: https://account.eyeson.team/api
  setup_complete_url: https://eyeson.team/slack/success
  faq_url: https://eyeson.team/slack/faq

production:
  eyeson_api: https://api.eyeson.team
  eyeson_account_api: https://account.eyeson.team/api
  setup_complete_url: https://eyeson.team/slack/success
  faq_url: https://eyeson.team/slack/faq
